[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
program = { path = "../program" }
risc0-zkvm = { version = "^2.0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
